/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeddingMeetingRouteImport } from './routes/wedding-meeting'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RomanticExperienceRouteImport } from './routes/romantic-experience'
import { Route as RestaurantPoolRouteImport } from './routes/restaurant-pool'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WeddingMeetingRoute = WeddingMeetingRouteImport.update({
  id: '/wedding-meeting',
  path: '/wedding-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RomanticExperienceRoute = RomanticExperienceRouteImport.update({
  id: '/romantic-experience',
  path: '/romantic-experience',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantPoolRoute = RestaurantPoolRouteImport.update({
  id: '/restaurant-pool',
  path: '/restaurant-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/restaurant-pool': typeof RestaurantPoolRoute
  '/romantic-experience': typeof RomanticExperienceRoute
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-meeting': typeof WeddingMeetingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/restaurant-pool': typeof RestaurantPoolRoute
  '/romantic-experience': typeof RomanticExperienceRoute
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-meeting': typeof WeddingMeetingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/restaurant-pool': typeof RestaurantPoolRoute
  '/romantic-experience': typeof RomanticExperienceRoute
  '/rooms': typeof RoomsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wedding-meeting': typeof WeddingMeetingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/restaurant-pool'
    | '/romantic-experience'
    | '/rooms'
    | '/sitemap.xml'
    | '/wedding-meeting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/restaurant-pool'
    | '/romantic-experience'
    | '/rooms'
    | '/sitemap.xml'
    | '/wedding-meeting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/restaurant-pool'
    | '/romantic-experience'
    | '/rooms'
    | '/sitemap.xml'
    | '/wedding-meeting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  RestaurantPoolRoute: typeof RestaurantPoolRoute
  RomanticExperienceRoute: typeof RomanticExperienceRoute
  RoomsRoute: typeof RoomsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeddingMeetingRoute: typeof WeddingMeetingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wedding-meeting': {
      id: '/wedding-meeting'
      path: '/wedding-meeting'
      fullPath: '/wedding-meeting'
      preLoaderRoute: typeof WeddingMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romantic-experience': {
      id: '/romantic-experience'
      path: '/romantic-experience'
      fullPath: '/romantic-experience'
      preLoaderRoute: typeof RomanticExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-pool': {
      id: '/restaurant-pool'
      path: '/restaurant-pool'
      fullPath: '/restaurant-pool'
      preLoaderRoute: typeof RestaurantPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  RestaurantPoolRoute: RestaurantPoolRoute,
  RomanticExperienceRoute: RomanticExperienceRoute,
  RoomsRoute: RoomsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeddingMeetingRoute: WeddingMeetingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
